baseURL = 'http://example.org/'
defaultContentLanguage = 'pt-br'
defaultContentLanguageInSubdir = true
title = 'Portfolio'

[languages]
   [languages.en]
    title = 'My blog'
    weight = 1
    languageName = 'English'
   [languages.pt-br]
    title = 'O meu blog'
    weight = 2
    languageName = 'Portuguese'

